### ISSUE TITLE
test

### ISSUE THREAD

**Issue by mljcisneros** [melitest/testrepo#1]
Issue que deberia representar que hay un xss en un proyecto.

**Comment by mljcisneros** [comment]
Este issue fue cerrado automáticamente, cuando el issue esté cerrado se considera en estado pendiente de revisión del equipo de seguridad web

**Comment by mljcisneros** [comment]
Este issue fue cerrado automáticamente, cuando el issue esté cerrado se considera en estado pendiente de revisión del equipo de seguridad web

**Comment by mljcisneros** [comment]
Este issue fue cerrado automáticamente, cuando el issue esté cerrado se considera en estado pendiente de revisión del equipo de seguridad web

**Comment by mljcisneros** [comment]
Este issue fue cerrado automáticamente, cuando el issue esté cerrado se considera en estado pendiente de revisión del equipo de seguridad web

**Comment by usermelitest** [comment]
This issue is in state pending
